### PR TITLE
Update `gimp`, migrate to `core24`

### PR DESCRIPTION
**Pull request by jnsgruk**
This is a bit of maintenance to ensure we're ready when GIMP 3.0 releases.

- Bumps gmic, which enables us to drop a patch I wrote last time
- Bumps rawtherapee, enabling us to drop another patch!
- Grab gimp from `master` for now, but moving to 2.99.19-rc soon

Edit: subsequent patches...

- Drop rawtherapee 
- Use libwmf & ghostscript from the archive
- Cleanup some explicit things taken care of by the gnome extension
- Remove evince (I can't see why we're shipping this in the snap?)

Edit (again!):

- Migrate to `core24` and use more libraries from the archive

### CODE REVIEW

**Review by lucyllewy — DISMISSED** [review]
LGTM

**Comment by jnsgruk** [comment]
Some updates (I've edited the PR description):

- Drop rawtherapee
- Use libwmf & ghostscript from the archive
- Cleanup some explicit things taken care of by the gnome extension
- Remove evince (I can't see why we're shipping this in the snap?)

**Review by lucyllewy — DISMISSED** [review]
LGTM

**Comment by brunvonlope** [comment]
> Remove evince (I can't see why we're shipping this in the snap?)

@jnsgruk This dep is there probably because of the custom print preview

**Comment by jnsgruk** [comment]
> > Remove evince (I can't see why we're shipping this in the snap?)
> 
> 
> 
> @jnsgruk This dep is there probably because of the custom print preview

Ah interesting. I'll update to just stage it from the archive then.

**Comment by jnsgruk** [comment]
This built, but didn't actually run due to a mismatch in `libharfbuzz` versions. I'm in the process of migrating the snap to 24.04, which should fix that.

**Comment by jnsgruk** [comment]
Updated to core24, but broke gmic in the process, will attempt to fix that next. So far these changes have made quite a nice simplification to the codebase, and also reduced the size of the snap by over 300MB!

**Comment by jnsgruk** [comment]
Last little hurdle now before this is ready! I get this error when I try to start Gmic...

image


If anyone knows how to solve this, I'm all ears... perhaps @kenvandine or @sergiusens?

**Comment by jnsgruk** [comment]
G'mic working! Will merge this so that a `candidate` build gets pushed that can be tested more easily by folks!

image

**Pull request merged**
