### PR TITLE
Update GIMP to new release

### PR DESCRIPTION
**Pull request by gjsman**

### CODE REVIEW

**Comment by popey** [comment]
Looks like there's some additional work to do as the bump_Babl-GEGL_versions.patch patch no longer applies. 

```
patching file app/sanity.c
Hunk #1 FAILED at 351.
Hunk #2 FAILED at 388.
2 out of 2 hunks FAILED -- saving rejects to file app/sanity.c.rej
patching file configure.ac
Hunk #1 FAILED at 40.
Hunk #2 FAILED at 519.
2 out of 2 hunks FAILED -- saving rejects to file configure.ac.rej
```

**Comment by Ads20000** [comment]
@diddledan any ideas?

**Comment by diddledan** [comment]
I've been working on getting the newer build working, but don't forget that it is a beta release from upstream so I might be hitting bugs that wouldn't ordinarily be there, and being beta we shouldn't feel an urgent need to get it out asap.

**Comment by diddledan** [comment]
I've got a built compiled but it is very broken - the ui loads but any plugins (e.g. python, gegl, etc.) fail to operate

**Comment by Ads20000** [comment]
@diddledan could you put your updates on GitHub somewhere so other people can have a look a play around if they want to? :)

**Comment by diddledan** [comment]
here you go: https://github.com/diddledan/gimp-snap/tree/beta-2.9.6

**Comment by diddledan** [comment]
This is now out of date. I'm closing the PR to tidy things up. I've been working on 2.10 and nearly have it building.

**Pull request closed without merging**
