### PR TITLE
bump gimp

### PR DESCRIPTION
**Pull request by popey**
This updates gimp to the latest release.
Had to update git URLs for gmic as it's moved. 
They also stopped supporting cmake, so switched to qmake.

### CODE REVIEW

**Comment by popey** [comment]
Built and briefly tested locally here.

Screenshot from 2023-10-08 01-41-08

**Comment by merlijn-sebrechts** [comment]
The build seems to be failing on arm. @popey or @lucyllewy,  do you want to continue to get the latest version at least on amd64, or do you want to fix the arm64 issues first?

**Comment by popey** [comment]
I'm stumped. I don't have an arm64 machine in which to test this. @lucyllewy any ideas?

```
Building libaom 
+ EXTRA=
+ '[' aarch64-linux-gnu = arm-linux-gnueabihf ']'
+ export DESTDIR=/data/parts/libaom/install
+ DESTDIR=/data/parts/libaom/install
+ cmake /data/parts/libaom/src -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_DOCS=OFF -DENABLE_EXAMPLES=OFF -DENABLE_TESTDATA=OFF -DENABLE_TESTS=OFF -DCONFIG_PIC=1 -DCONFIG_AV1_ENCODER=1 -DCONFIG_AV1_DECODER=1 -DCONFIG_MULTITHREAD=1
error: unknown command "/data/parts/libaom/src", see 'snap help'.
Failed to run 'override-build': Exit code was 64.
Error: The process '/usr/bin/docker' failed with exit code 2
```

According to the store stats, around 0.2% of users are on the arm64 build. 99.4% are on amd64.

**Comment by popey** [comment]
@soumyaDghosh, let's continue the conversation about your work on your PR, as it's quite a comprehensive change.

For this PR, which I'm doing minor changes to get 2.10.34 out the door, I have rolled back the version of libaom to a version I know used to build on core20, so it builds on arm64. 

I have test-built this in Launchpad. It gets past libaom, so I am somewhat confident this will build in the GitHub action. So I have pushed this one-line change to get it building. Let's see if this works, and if it does, get this merged so we get 2.10.34 built in edge, and can test it.

**Comment by popey** [comment]
This failed build is a *lie* and we should not trust it. 
This PR built perfectly fine in [Launchpad](https://launchpad.net/~popey/+snap/snapcraft-gimp-b7394b013ff894e8064493b3811462a5/+build/2260739), which matters because that's how the published builds in the store are made. 
Please can this PR be merged @merlijn-sebrechts ? 
We can investigate the errant GH action separately - which I have filed #244 for.

**Review by merlijn-sebrechts — APPROVED** [review]
Thanks for putting in all this work, @popey!

**Pull request merged**
