### PR TITLE
Fix `preview` branch build and enable automation

### LINKED ISSUE #126: GIMP 2.99.2 Released
GIMP 2.99.2 Released
https://www.gimp.org/news/2020/11/06/gimp-2-99-2-released/

### LINKED ISSUE #219: [Bug]: gimp 2.99.10 "error while loading shared libraries: libgimpwidgets-3.0.so.0: cannot open shared object file: No such file or directory"
### What happened?

The app crashes during startup with the following error:

```shell
 ~ snap list|grep gimp 
gimp                  2.99.10                     397    preview/edge   snapcrafters        -
 ~ gimp
/snap/gimp/397/usr/bin/gimp: error while loading shared libraries: libgimpwidgets-3.0.so.0: cannot open shared object file: No such file or directory
~
```

### What should have happened?

The app starts up normally

### Output of `snap info $snap_name`

```shell
~ snap info gimp
name:      gimp
summary:   GNU Image Manipulation Program
publisher: Snapcrafters
store-url: https://snapcraft.io/gimp
contact:   https://github.com/snapcrafters/gimp/issues
license:   unset
description: |
  Whether you are a graphic designer, photographer, illustrator, or scientist, GIMP provides you
  with sophisticated tools to get your job done. You can further enhance your productivity with GIMP
  thanks to many customization options and 3rd party plugins.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
  
  Upstream Project: https://www.gimp.org/
  snapcraft.yaml Build Definition:
  https://github.com/snapcrafters/gimp/blob/master/snap/snapcraft.yaml
commands:
  - gimp
snap-id:      KDHYbyuzZukmLhiogKiUksByRhXD2gYV
tracking:     preview/edge
refresh-date: today at 10:26 GMT
channels:
  latest/stable:     2.10.30 2022-08-19 (393) 546MB -
  latest/candidate:  ↑                              
  latest/beta:       ↑                              
  latest/edge:       2.10.32 2022-08-23 (399) 547MB -
  preview/stable:    –                              
  preview/candidate: –                              
  preview/beta:      –                              
  preview/edge:      2.99.10 2022-08-17 (397) 650MB -
installed:           2.99.10            (397) 650MB -
```

### Output of `snap connections $snap_name`

```shell
~ snap connections gimp
Interface               Plug                  Slot                            Notes
browser-support         gimp:browser-support  :browser-support                -
content[gnome-42-2204]  gimp:gnome-42-2204    gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   gimp:gtk-3-themes     gtk-common-themes:gtk-3-themes  -
content[icon-themes]    gimp:icon-themes      gtk-common-themes:icon-themes   -
content[sound-themes]   gimp:sound-themes     gtk-common-themes:sound-themes  -
cups-control            gimp:cups-control     -                               -
dbus                    -                     gimp:dbus-gimp                  -
desktop                 gimp:desktop          :desktop                        -
desktop-legacy          gimp:desktop-legacy   :desktop-legacy                 -
gsettings               gimp:gsettings        :gsettings                      -
home                    gimp:home             :home                           -
network                 gimp:network          :network                        -
opengl                  gimp:opengl           :opengl                         -
removable-media         gimp:removable-media  -                               -
unity7                  gimp:unity7           :unity7                         -
wayland                 gimp:wayland          :wayland                        -
x11                     gimp:x11              :x11                            -
```

### Output of `snap version`

```shell
~ snap version
snap    2.58
snapd   2.58
series  16
ubuntu  22.10
kernel  5.19.0-29-generic
```

### Relevant log output

```shell
~ dmesg -w

[21876.408342] audit: type=1400 audit(1675075090.857:583): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/17950/usr/lib/snapd/snap-confine" pid=490593 comm="snap-confine" capability=12  capname="net_admin"
[21876.408348] audit: type=1400 audit(1675075090.857:584): apparmor="DENIED" operation="capable" class="cap" profile="/snap/snapd/17950/usr/lib/snapd/snap-confine" pid=490593 comm="snap-confine" capability=38  capname="perfmon"
```

### Teminal output of app

```shell
~ /snap/bin/gimp
/snap/gimp/397/usr/bin/gimp: error while loading shared libraries: libgimpwidgets-3.0.so.0: cannot open shared object file: No such file or directory
```

### LINKED ISSUE #244: [Enhancement]: fix/rewrite/rework the build-pr action
### What changes would you like?

The [build-prs](https://github.com/snapcrafters/gimp/blob/master/.github/workflows/build-prs.yml) GitHub action [fails](https://github.com/snapcrafters/gimp/actions/runs/6510642035/job/17684768729?pr=242) to build sometimes, when the snap builds fine in Launchpad.

A quick and dirty workaround could be to disable `arm64` in the action yaml (the same way `armhf` is disabled)

A better solution *might* be to use `snapcraft remote-build` which actually builds in Launchpad which is a way more consistent way to build, given that's how we actually publish builds from.

### Any extra information?

_No response_

### PR DESCRIPTION
**Pull request by jnsgruk**
This PR adds new automation to the `preview` branch. It depends on https://github.com/snapcrafters/ci/pull/28, and should not be merged before that PR.

These files are very similar to those on the `candidate` branch, but specify a different channel. 

@merlijn-sebrechts before this can be merged, we need to create an environment named "Preview Candidate Branch" which has all the necessary secrets in it, noting the name of `${{ secrets.SNAP_STORE_PREVIEW_STABLE }}`.

Let me know what you think!

**Edit***: This grew arms and legs - it turns out the preview build was actually quite broken, and took some significant wrangling to get it to build and launch on Ubuntu. I've tried to break down into small commits where possible, but let me know if there is any further context required!

Closes #244 
Fixes #126 
Fixes #219

### CODE REVIEW

**Comment by jnsgruk** [comment]
Oh I didn't realise the build was broken, I'll take a look at that soon. The other option is to merge these relatively trivial changes, and we can address the build issues in another PR?

**Comment by merlijn-sebrechts** [comment]
I'd like you to fix the build first, either in this PR or in a separate one, so we can immediately test everything after merging.

**Comment by jnsgruk** [comment]
Latest commit grabs the changes from #202 and integrates them here.

**Comment by jnsgruk** [comment]
This last commit builds fine on my box.

I also noticed that gmic is missing here - I'm 95% through porting that for core22 / gimp 2.99 but not quite finished - will leave on a separate branch unless I finish before this merges :)

**Comment by jnsgruk** [comment]
@merlijn-sebrechts this is now actually "working", but the job takes too long and is killed by Github Actions (we can't make it timeout after a longer time without paying).

Are you happy to merge this? I'll need to have a think about what we can do for the PR flow in the case that the build takes *ages*!

What I can't work out is why the build on `candidate` can apparently build inside Github Actions in 42 minutes, and this timed out at six hours. I think something is stalling but I can't work out what,

**Comment by jnsgruk** [comment]
Latest commit tested with `remote-build` - resulting snap enabled this screenshot to happen :)

image

**Comment by jnsgruk** [comment]
This is now good to go from my side -- both architectures build fine on Launchpad as of today!

**Comment by jnsgruk** [comment]
@merlijn-sebrechts success! We have a green CI run for the pull request flow! (see [here](https://github.com/snapcrafters/gimp/actions/runs/7797080099?pr=255)).

I've removed the commit that enabled it to trigger, because I had to loosen the branch constraint on the pull request flow, but I think I can fix that in a later request when we try to converge the two branches?

**Review by merlijn-sebrechts — APPROVED** [review]
LGTM!

**Pull request merged**
