### PR TITLE
Switch to LZO Compression

### PR DESCRIPTION
**Pull request by diddledani**
Fixes: #167

Signed-off-by: Dani Llewellyn <diddledani@ubuntu.com>

### CODE REVIEW

**Comment by kenvandine** [comment]
Looks good

**Comment by diddledani** [comment]
I can't merge this without an approving review - Ken said it looks good but didn't mark it as an approved review.

**Review by AlanGriffiths — APPROVED** [review]
Yup

**Comment by diddledani** [comment]
Thanks Alan.

**Pull request merged**
